baseurl: ''
permalink: pretty
title: 'Road to Blue'

logo:
  mobile: "images/logo/logo-mobile.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.svg"
  desktop_height: "32px"
  desktop_width: "120px"

home: 
  limit_issues: 3

collections:
  issues:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "issues"
    values:
      layout: "issue"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
  - jekyll-datapage-generator

page_gen:
- data: candidates
  template: 'elected'
  dir: 'candidates'
  index_files: false
  name_expr: (record['First'] + "-" + record['Last']).gsub(' ', '-').downcase
  title_expr: record['First'] + " " + record['Last']

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
